export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";

export const CART_PRODUCT_REQUEST = "CART_PRODUCT_REQUEST";
export const CART_PRODUCT_FAILURE = "CART_PRODUCT_FAILURE";
export const CART_GET_PRODUCT_SUCCESS = "CART_GET_PRODUCT_SUCCESS";
export const CART_POST_PRODUCT_SUCCESS = "CART_POST_PRODUCT_SUCCESS";
export const CART_DELETE_PRODUCT_SUCCESS = "CART_DELETE_PRODUCT_SUCCESS";
export const CART_PATCH_PRODUCT_SUCCESS = "CART_PATCH_PRODUCT_SUCCESS";
